import Foundation

/// The line under the greeting — not a template, but something bob actually
/// wrote about *your* day, pulled from his memory, the last session, what's
/// playing, and the hour. "still chasing that lootgo bug from last night?"
/// It's the first thing that makes bob feel like he remembers you walked away.
///
/// Generated by a fast, silent one-shot claude call (never touches the chat),
/// cached for 30 minutes, and it NEVER blocks the idle screen — the greeting
/// shows instantly; this fades in when (and if) it's ready.
@MainActor
final class OpenLine: ObservableObject {
    static let shared = OpenLine()

    @Published private(set) var line: String?

    private let cacheURL: URL
    private var generating = false
    private var lastAttempt: Date?
    private let maxAgeSec: TimeInterval = 30 * 60
    private let minRetrySec: TimeInterval = 5 * 60

    private init() {
        cacheURL = BobHome.shared.root
            .appendingPathComponent("state", isDirectory: true)
            .appendingPathComponent("open-line.txt")
        // show a cached line instantly if we have one
        if let cached = try? String(contentsOf: cacheURL, encoding: .utf8) {
            let trimmed = cached.trimmingCharacters(in: .whitespacesAndNewlines)
            if !trimmed.isEmpty { line = trimmed }
        }
    }

    /// Refresh if the cached line is stale. Safe to call on every appear/idle.
    func refreshIfStale() {
        guard !generating else { return }
        if let attrs = try? FileManager.default.attributesOfItem(atPath: cacheURL.path),
           let mtime = attrs[.modificationDate] as? Date,
           Date().timeIntervalSince(mtime) < maxAgeSec {
            return // cache still fresh
        }
        // back off failures: don't re-spawn claude on every launch/idle if a
        // recent attempt didn't produce a cache (slow/failed generation).
        if let la = lastAttempt, Date().timeIntervalSince(la) < minRetrySec {
            return
        }
        generate()
    }

    private func generate() {
        guard !generating else { return }
        generating = true
        lastAttempt = Date()

        let nowPlaying: String = {
            if let t = MusicService.shared.current, t.state == "playing", let track = t.track {
                return "he's listening to \(track.name) by \(track.artist)."
            }
            return ""
        }()

        let fmt = DateFormatter()
        fmt.dateFormat = "EEEE h:mm a"
        let when = fmt.string(from: Date())

        // With the `open-line` lens, what bob reads (and how he sounds doing it)
        // lives in lenses/open-line.md — editable without touching Swift. The
        // prompt then carries only the task and the live facts of this moment.
        let lensedPrompt = """
        it's \(when) (IST). \(nowPlaying)
        write ONE short lowercase line you'd open with to pawan right now — like a bro picking up where you left off. under 14 words. no greeting word (shown separately). no quotes, no preamble — output only the line.
        """
        // No lens on disk (or a broken one) — the hand-typed original, verbatim.
        let plainPrompt = """
        you are bob. read USER.md, the last ~15 lines of MEMORY.md, and the last few lines of log.md in this directory. it's \(when) (IST). \(nowPlaying)
        write ONE short lowercase line you'd open with to pawan right now — like a bro picking up where you left off. reference something real and recent if it fits (a project, a thread you two had, the hour, the music). keep it under 14 words. do NOT start with a greeting word like hey/morning/evening (that's shown separately). no quotes, no preamble — output only the line.
        """

        let root = BobHome.shared.root
        Task.detached(priority: .utility) {
            // resolved here, off the main thread — resolve() reads files
            let lens = LensStore.shared.resolve("open-line")
            let result = Self.runClaude(
                prompt: lens == nil ? plainPrompt : lensedPrompt,
                systemPrompt: lens?.text,
                cwd: root
            )
            await MainActor.run {
                self.generating = false
                guard let raw = result else { return }
                let cleaned = Self.clean(raw)
                guard !cleaned.isEmpty else { return }
                self.line = cleaned
                try? cleaned.write(to: self.cacheURL, atomically: true, encoding: .utf8)
            }
        }
    }

    /// One clean line out of whatever claude printed.
    private static func clean(_ s: String) -> String {
        var t = s.trimmingCharacters(in: .whitespacesAndNewlines)
        // take the last non-empty line (claude sometimes prefixes chatter)
        if let last = t.split(separator: "\n").map({ $0.trimmingCharacters(in: .whitespaces) }).last(where: { !$0.isEmpty }) {
            t = last
        }
        t = t.trimmingCharacters(in: CharacterSet(charactersIn: "\"'"))
        return String(t.prefix(120))
    }

    private nonisolated static func runClaude(prompt: String, systemPrompt: String? = nil, cwd: URL) -> String? {
        var env = ProcessInfo.processInfo.environment
        for key in ["CLAUDECODE", "CLAUDE_CODE_ENTRYPOINT", "CLAUDE_CODE_SSE_PORT",
                    "CLAUDE_CODE_SESSION_ID", "CLAUDE_PROJECT_DIR"] {
            env.removeValue(forKey: key)
        }
        let process = Process()
        process.executableURL = URL(fileURLWithPath: ClaudeBridge.claudePath)
        var args = ["-p", "--permission-mode", "auto"]
        if let systemPrompt { args += ["--append-system-prompt", systemPrompt] }
        args.append(prompt)
        process.arguments = args
        process.currentDirectoryURL = cwd
        process.environment = env
        let pipe = Pipe()
        process.standardOutput = pipe
        // never a Pipe: nothing drains it here, and 64K of CLI noise would wedge
        // the process against `waitUntilExit()`. Same log as the chat bridge.
        process.standardError = ClaudeBridge.stderrSink(root: cwd)
        do {
            try process.run()
            // watchdog: never let a wedged subprocess hold `generating` forever.
            let watchdog = DispatchWorkItem { [weak process] in
                if process?.isRunning == true { process?.terminate() }
            }
            DispatchQueue.global().asyncAfter(deadline: .now() + 45, execute: watchdog)
            process.waitUntilExit()
            watchdog.cancel()
            let data = pipe.fileHandleForReading.readDataToEndOfFile()
            guard process.terminationStatus == 0 else { return nil }
            return String(data: data, encoding: .utf8)
        } catch {
            return nil
        }
    }
}
